import type { Metadata } from "next";
import { Google_Sans } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation/Navigation";

const googleSans = Google_Sans({
  variable: "--font-google-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Linda Zaeske - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${googleSans.variable} h-full antialiased`}
    >
      <body className="min-h-full">
              <Navigation />

        {children}</body>
    </html>
  );
}
